name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore S4M/S4M.sln
    - name: Build
      run: dotnet build S4M/S4M.sln --no-restore
    - name: Test
      run: dotnet test S4M/S4M.sln --no-build --verbosity normal
